name: Deploy to VPS

on:
  push:
    branches:
      - main   # sau branch-ul pe care vrei să faci deploy automat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh ubuntu@81.181.199.140 "cd /home/dionix/ && git pull && sudo pm2 restart dionix-site"
